# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Poliklinika Jelovac
titles:
  hr: Poliklinika Jelovac
  en: Polyclinic Jelovac
# email: your-email@example.com
phone: +385 52 686 645
mobile: +385 91 166 8801
address: Kmačići 22a, 52444 Tinjan
description: >- # this means to ignore newlines until "baseurl:"
  Your trusted healthcare provider in the community. We provide quality healthcare and professional service to all our patients
  focusing on ultrasound, color doppler, diagnostics and prevention.
descriptions:
  hr: Vaš pouzdani pružatelj zdravstvenih usluga u zajednici. Pružamo kvalitetnu zdravstvenu skrb i profesionalnu uslugu svim našim pacijentima s fokusom na ultrazvuk, color doppler, dijagnostiku i prevenciju.
  en: Your trusted healthcare provider in the community. We provide quality healthcare and professional service to all our patients, focusing on ultrasound, colour doppler, diagnostics and prevention.
baseurl: ""
url: "https://www.poliklinika-jelovac.hr"
author: 🩺 dr.med. Nedjeljko Jelovac

keywords:
  hr: "ultrazvuk, color doppler, dijagnostika, prevencija, poliklinika, dr. Jelovac, Tinjan, Istra, rana dijagnostika, zloćudne bolesti"
  en: "ultrasound, colour doppler, diagnostics, prevention, polyclinic, dr. Jelovac, Tinjan, Istria, early diagnostics, cancer prevention"

# Language settings
languages: ["hr", "en"]
language_icons: {
  hr: "/assets/lang-hr.png",
  en: "/assets/lang-uk.png"
}
default_lang: "hr"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - pages/hr/services.html
  - pages/hr/contact.html
  - pages/hr/about.markdown
  - pages/en/services.markdown
  - pages/en/contact.html
  - pages/en/about.markdown
# Exclude from processing
exclude:
  - _en/_posts
  - _hr/_posts

# Defaults for all pages
defaults:
  - scope:
      path: "pages/hr"
      type: pages
    values:
      lang: hr
  - scope:
      path: "pages/en"
      type: pages
    values:
      lang: en

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/